### ISSUE TITLE
Preview: Add details config docs - especially running as a service

### ISSUE THREAD

**Issue by bryanmacfarlane** [Microsoft/vsts-agent#105]

**Comment by apacha** [comment]
I've tried running the preview on my Mac, but I can't get past the point, where it wants to add the agent to the agent pool and fails with `VS30063: You are not authorized to access` ... or `TF400813: Resource not available for anonymous access. Client authentication required.`.

However, there was no possibility to provide a user-name or something alike. If there is a possible configuration option for this, it would be great to add it to the documentation.

**Comment by bryanmacfarlane** [comment]
Can you add your configuration terminal input/output?

**Comment by apacha** [comment]
```
Maple-Mini:VstsBuildAgent alex$ cd vsts-agent-darwin-2.99.0-0428/
Maple-Mini:vsts-agent-darwin-2.99.0-0428 alex$ ls
bin		externals	run.cmd		run.sh
Maple-Mini:vsts-agent-darwin-2.99.0-0428 alex$ ./run.sh 

>> End User License Agreements:

Building sources from a TFVC repository requires accepting the Team Explorer Everywhere End User License Agreement. This step is not required for building sources from Git repositories.

A copy of the Team Explorer Everywhere license agreement can be found at:
  /Users/alex/VstsBuildAgent/vsts-agent-darwin-2.99.0-0428/externals/tee/license.html

Enter accept the Team Explorer Everywhere license agreement now? (Y/N) (press enter for N) > y
Enter a valid value for accept the Team Explorer Everywhere license agreement now? (Y/N).
Enter accept the Team Explorer Everywhere license agreement now? (Y/N) (press enter for N) > Y

>> Connect:

Enter server URL > https://sightplayer.visualstudio.com
Enter authentication type (press enter for PAT) > 
Enter personal access token > ****************************************************
Connecting to server ...
Saving credentials...

>> Register Agent:

Enter agent pool (press enter for default) > 
VS30063: You are not authorized to access https://sightplayer.visualstudio.com.
Failed to find pool name. Try again or ctrl-c to quit
Enter agent pool (press enter for default) > Default
TF400813: Resource not available for anonymous access. Client authentication required.
Failed to find pool name. Try again or ctrl-c to quit
Enter agent pool (press enter for default) > MaxOSX
TF400813: Resource not available for anonymous access. Client authentication required.
Failed to find pool name. Try again or ctrl-c to quit
Enter agent pool (press enter for default) > Exiting...

```

**Comment by bryanmacfarlane** [comment]
Interesting.  Can't repo (of course :))

Any clues in ./_diag/ agent logs?
Any proxies involved here?
Added that account to both roles?  https://github.com/Microsoft/vsts-agent/blob/master/README.md

**Comment by apacha** [comment]
Obviously, I forgot to add the user to _both_ roles. Just added them and now it seems to work. Just out of curiousity - does the PAT already contain the user-name, because I was never required to add it anywhere.

**Comment by bryanmacfarlane** [comment]
We should make the error more actionable.  We're also improving.  Soon you will only have to be in one

**Comment by apacha** [comment]
BTW: The documentation definitely must contain a section about how to configure paths on a MacOSX. I've been trying for hours now to set up my Xamarin.iOS build with the agent, but for some reasons, the agent can neither find `nuget`, `mono` nor `xbuild` in my path, although they work, when I execute them from the command line.

I've tried the following, but nothing succeeded yet:

- Add User capabilities in VSTS Control panel (e.g. mono - /Library/Frameworks/Mono.framework/Versions/Current/bin/mono)
- Specifying absolute paths in the build script (does not work, because some build steps don't allow for customization, e.g. Build Xamarin.iOS solution or Xamarin Component Restore)
- Trying to configure the path with a custom step that executes the following command in a bash "export PATH=/Library/Frameworks/Mono.framework/Versions/Current/bin/:${PATH}" before the rest of the build. Did not work, because there seems to be no way to add quotation marks into the arguments field, without them being screwed up once they are sent to the agent.
- Adding the corresponding paths as administrator to /etc/paths for all users.

No success so far :-(
Any ideas, why the agent that is running as service is not able to access the correct paths from the system?

**Comment by bryanmacfarlane** [comment]
All docs updated.

The 2.100.1 release also supports a .Path file for the service.  Also added service docs.

https://github.com/Microsoft/vsts-agent/blob/master/README.md

**Comment by apacha** [comment]
.Path worked like a charm. Thanks a lot!
