### ISSUE TITLE
Run agent in Service mode

### ISSUE THREAD

**Issue by jachakrohit07** [Microsoft/vsts-agent#1058]
Can you please specify in detail how I can run the build agent on the TFS server in the "Service mode" as the build agent stops working sometimes just before the release to the production?

**Comment by TingluoHuang** [comment]
@jachakrohit07 here is the doc for agent config https://www.visualstudio.com/en-us/docs/build/actions/agents/v2-windows#download-and-configure-the-agent

can you share detail error you get?

**Comment by jachakrohit07** [comment]
To run the agent interactively I type " C:\Agent\Agent\VsoAgent.exe" in the command prompt on my TFS server. But to use it in the "Service" mode, what are the commands for it?

**Comment by TingluoHuang** [comment]
@jachakrohit07 you need config the agent as windows service, please follow doc to configure the agent
https://www.visualstudio.com/en-us/docs/build/actions/agents/v1-windows#download-and-configure-the-agent

also, looks like you are using 1.x agent, please consider switch to use 2.x agent, since 1.x has been deprecated.

**Comment by TingluoHuang** [comment]
Thanks for the explanation.
Today our [vsts-agent](https://github.com/microsoft/vsts-agent) produces 5 self-contained packages for different platforms. `win7-x64, ubuntu16-x64, ubuntu14-x64, osx10.11-x64, redhat7.2-x64`

We consider adopt netcore 2.0 since it will support on more OS and i can just build Linux-x64 for all linux flavors.

I guess if we still want to support customers to use vsts-agent on `osx10.11` and `redhat7.2`. we need use netcore1.1 build those packages.
`win7-x64 (netcore2.0)`
`Linux-x64 (netcore2.0)`
`osx10.12-x64 (netcore2.0)`
`redhat7.2-x64 (netcore1.1)`
`osx10.11-x64 (netcore1.1)`

**Comment by jachakrohit07** [comment]
I have urgent question regarding changeset report generation in tfs as I
want to link changeset id to tasks in the report. Please help  I tried
following query but final result gives no rows.

SELECT DISTINCT --df.[FileName]
    --,df.FilePath
    dwi.System_title AS 'Title'
    ,dcs.ChangesetID AS 'ChangeSetID'
    ,dwi.System_id AS 'WorkItemID'
    ,dwi.System_WorkItemType
    ,dwi.System_State
    ,dwi.System_CreatedDate
    ,dwi.System_ChangedDate

FROM DimFile df
JOIN FactCodeChurn fcc ON df.FileSK = fcc.FilenameSK
JOIN FactWorkItemChangeset fwi ON fcc.ChangesetSK = fwi.ChangesetSK
JOIN DimWorkItem dwi ON fwi.WorkItemID = dwi.System_id
AND fwi.TeamProjectCollectionSK = dwi.TeamProjectCollectionSK
AND fwi.RemovedDateTime = CONVERT(DATETIME, N'9999', 126)
JOIN DimChangeset dcs ON dcs.ChangesetSK = fcc.ChangesetSK

WHERE dwi.System_revisedDate = CONVERT(DATETIME, N'9999', 126)
--AND df.FilePath LIKE '%$repositorylocation%'
--AND dwi.System_WorkItemType IN ('Product Backlog Item', 'Task', 'Bug')

ORDER BY dcs.ChangesetID
