### ISSUE TITLE
Build artifacts are not being deleted

### ISSUE THREAD

**Issue by RoyRosenberg** [Microsoft/vsts-agent#1302]
Hi guys,

TFS 2017 (without updates)
Build Agent version: 2.105.7 on Win Server 2012 R2

We have a build with publish artifacts task to a file share:
![build3](https://user-images.githubusercontent.com/18610554/33005185-6b40aa66-cdcd-11e7-9345-cd1323d0dfbf.png)

The build has this retention policy:
![build1](https://user-images.githubusercontent.com/18610554/33005232-935986b2-cdcd-11e7-8298-4862d03b627d.png)

for some reason, the build artifacts are not being deleted, here's a screenshot for the drop, you can see that the build folders exist and not deleted:
![build2](https://user-images.githubusercontent.com/18610554/33005339-0c31c748-cdce-11e7-8686-56552f3a40e5.png)

The build\TFS should delete the artifacts folder but don't.. please help
Thanks!
Roy

**Comment by saranad** [comment]
Few things to check
What happens if you queue a test build which publishes a drop to the same share and if you delete it manually? I am just trying to make sure that there is some agent which can access this share and delete the drop.
Can you attach the snapshot of your entire retention settings? Are these drops related to Pull Requests? If yes, then please add an explicit policy for PR branches as mentioned here - https://docs.microsoft.com/en-us/vsts/build-release/concepts/policies/retention - Cleaning up your PR builds.

**Comment by RoyRosenberg** [comment]
saranad,
I just checked another builds that run on different agents\machines and it behaves the same.. the drops are not being deleted.... 
The build is TFVC and not git.
here are the full retention settings:
![build4](https://user-images.githubusercontent.com/18610554/33114468-a79220be-cf65-11e7-9c80-615324f9dc08.png)

**Comment by bryanmacfarlane** [comment]
agent doesn't do retention.  so not an issue here.   The service does retention
