### ISSUE TITLE
Special characters in password while using unattended

### ISSUE THREAD

**Issue by balfa666** [Microsoft/vsts-agent#1335]
## Have you try trouble shooting doc?
Link to trouble shooting doc: https://www.visualstudio.com/en-us/docs/build/troubleshooting

## Agent version and platform
Version of your agent? 2.126

OS of the machine running the agent? Windows Server 2012 R2

## VSTS type and version
On-Prem TFS 2017 update 2

## What's not working?
Are special characters in password while using unattended installation forbidden? If not, could you help me with the command line syntax?
If i specify the same password in interactive mode it works perfectly fine.

**Comment by ericsciple** [comment]
the escaping rules depend on the shell you are using

**Comment by ericsciple** [comment]
on windows `cmd /?` for cmd escaping rules, or for powershell using the single quoted string might be the easiest route, since single quote is the only character you need to handle. for example: `'this string has an escaped '' single quote'`

**Comment by balfa666** [comment]
I'm using powershell.

I've tried 
"$password = "&67^98jhuHyg" 
"$password = '&67^98jhuHyg'
"$password = ConvertTo-SecureString "&67^98jhuHyg" -AsPlainText -Force"
"$password = ConvertTo-SecureString '&67^98jhuHyg' -AsPlainText -Force"

First 2 fail with: Unrecognized command-line input arguments: 'windowsLogonPassword'
2 other fail with ""Invalid windows credentials entered.""

& $agentExecutablePath --unattended --url $tfsServer --auth PAT --token $TFSToken --pool $poolName --agent $agentName --work $workDir --runAsService --windowsLogonAccount $ServiceAccountUserName --windowsLogonPassword $password

**Comment by ericsciple** [comment]
it would be better to use the env var `VSTS_AGENT_INPUT_<ARGUMENT_NAME>`, check `.\config.cmd --help`

**Comment by ericsciple** [comment]
also you cannot pass a secure string from powershell to a command line application

**Comment by balfa666** [comment]
Anywhere i can find more info for environment variables? Config --help does not list much

**Comment by ericsciple** [comment]
```powershell
$env:VSTS_AGENT_INPUT_WINDOWSLOGONPASSWORD = '&67^98jhuHyg'
$env:VSTS_AGENT_INPUT_TOKEN = $TFSToken

& $agentExecutablePath --unattended --url $tfsServer --auth PAT --pool $poolName --agent $agentName --work $workDir --runAsService --windowsLogonAccount $ServiceAccountUserName
```

**Comment by balfa666** [comment]
Many thanks. Everything works great. Last question, should i always use those variables for all arguments?

**Comment by ericsciple** [comment]
Typically I prefer passing arguments on the command line, since that is the common pattern.

However, I prefer passing arguments as environment variables when either of the following are true:
1. The argument contains hard to escape sequences. Not only does the shell you are using come into play, but also how the downstream application is parsing the command line. Generally it's not too much of a problem, but everyonce in a while there is a problematic sequence for a specific shell, or the downstream application parsing rules are not great.
2. The argument contains sensitive information. Command lines can get logged in many ways. For example in your powershell user command history. Also some organizations turn on command line auditing which would leave the full command in the security log https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/manage/component-updates/command-line-process-auditing Also dumping running processes on some operating systems can reveal the full command line, even across user sessions.

**Comment by balfa666** [comment]
Thanks for all your help. Have a nice day
