### ISSUE TITLE
Assets is empty in API feed for latest release?

### ISSUE THREAD

**Issue by jdholbrook81** [Microsoft/vsts-agent#1354]
https://api.github.com/repos/Microsoft/vsts-agent/releases/latest

assets shows as:
  "assets": [

  ],

Assets are shown in the release notes: https://github.com/Microsoft/vsts-agent/releases/latest

Was using this to pull down latest agent as part of an agent build.

**Comment by ppanyukov** [comment]
Yes, this has completely broken our agent auto-update on restart feature, effectively rendering all our agents dead.

In fact, the whole URL scheme has changed for downloads.

**v2.124.0 and earlier** we'd use this URL:

```
https://github.com/Microsoft/vsts-agent/releases/download/v${VSTS_LATEST_VERSION}/vsts-agent-rhel.7.2-x64-${VSTS_LATEST_VERSION}.tar.gz

e.g.

https://github.com/Microsoft/vsts-agent/releases/download/v2.107.1/vsts-agent-rhel.7.2-x64-2.107.1.tar.gz
```

**AFTER v2.124.0** the URL scheme becomes very different:

```
https://vstsagentpackage.azureedge.net/agent/${VSTS_LATEST_VERSION}/vsts-agent-linux-x64-${VSTS_LATEST_VERSION}.tar.gz

e.g.

https://vstsagentpackage.azureedge.net/agent/2.126.0/vsts-agent-linux-x64-2.126.0.tar.gz
```

The host is different, the path is different, the name of the tar is different. 

Basically, completely not backward compatible :)

We can fix this on our end of course but I must say this is rather very inconvenient.

**Comment by TingluoHuang** [comment]
@jdholbrook81 @ppanyukov we used github as a storage for the agent package before, and now we start using Azure Blob Storage for the agent package, the back compat is built-in to VSTS. Your script should query VSTS to get the latest agent package location.

https://github.com/Microsoft/vsts-agent/issues/1333

**Comment by TingluoHuang** [comment]
@ppanyukov can you provide more detail about your `agent auto-update on restart feature`?

**Comment by ppanyukov** [comment]
@TingluoHuang we have agent startup bash script which goes along these lines:

```
CURRENT_AGENT_VERSION=$(get_installed_version)
LATEST_AGENT_VERSION=$(get_lastest_released_version)

if "${CURRENT_AGENT_VERSION}" != "${LATEST_AGENT_VERSION}"
then
   download_agent ${LATEST_AGENT_VERSION}
   install_agent ${LATEST_AGENT_VERSION}
fi
```

We implemented this to primarily resolve the following issue:

- VSTS (visualstudio.com) would occasionally tell the agent that it is too old, and tell it to shutdown. Since we use docker with `autorestart=always` policy, docker would restart the container, but then the agent would be told that it's too old and it would shut down, etc ad infinitum -- infinite loop.

Additional benefit of this feature for us is that it's very easy to keep the agent on latest version without having to build new docker images for it -- simply restart the container.

**Comment by jdholbrook81** [comment]
The unfortunate side of querying VSTS is we have to manage another PAT.

**Comment by TingluoHuang** [comment]
@jdholbrook81 I assume your already have to manage a PAT for agent config, right? that PAT should work.

**Comment by jdholbrook81** [comment]
@TingluoHuang currently we do the config during release. Build pulls the agent and then config happens on a per environment basis during release. We could refactor this of needed. but would like to avoid.

**Comment by bryanmacfarlane** [comment]
The backend of VSTS of where the agent is located is the definitive truth.  That was intentional so we could change locations in the future (we always knew we would move assets to a CDN).  If you query the VSTS backend, you'll notice a list of versions - some pointing to GH release urls and some pointing to the new CDN.

Ting, is there a way to set the assets collection pointing to the CDN location via the GH rest api?

**Comment by TingluoHuang** [comment]
@bryanmacfarlane no you can't, the only way to set the assets collection for github release is to upload a file.
Should we upload the agent package to both location? github and CDN
So, folks from github can still query github release assets, and users from VSTS/TFS/AgentUpdate will use Azure CDN.

**Comment by bryanmacfarlane** [comment]
@TingluoHuang - maybe we can upload a json file with location info where to get from CDN.  That at least avoids the pain mentioned above of maintaining a PAT to query VSTS.  They just do a get on that file and then follow it.

**Comment by TingluoHuang** [comment]
#1644

**Comment by TingluoHuang** [comment]
Close this issue, the next agent release will contains an assets.json file which contains agent download info.
