### ISSUE TITLE
Agent 2.126.0 not working with system level proxy

### ISSUE THREAD

**Issue by omeshp** [Microsoft/vsts-agent#1374]
## Agent version and platform
Version of your agent? 2.126.0, 2.119.1

OS of the machine running the agent? Windows

## VSTS type and version
VisualStudio.com

If VisualStudio.com, what is your account name? http://nestle-nppc.visualstudio.com

## What's not working?
Agent version 2.116.1 is able to work with system level proxy, but agent version 2.119.1 or 2.126.0 is not honoring system level proxy.

## Agent and Worker's diag log
[Agent_20180111-145612-utc.log](https://github.com/Microsoft/vsts-agent/files/1632392/Agent_20180111-145612-utc.log)

**Comment by bryanmacfarlane** [comment]
This is as designed.  

The docs have always dictated that the agent needs to be configured for the proxy.  The agent instructions have never stated we respect (and can't) the system level proxy.

https://docs.microsoft.com/en-us/vsts/build-release/actions/agents/proxy?tabs=windows
https://github.com/Microsoft/vsts-agent/blob/master/docs/start/proxyconfig.md

2.116.1 had a bug where some of the core agent would sort of work with a system level proxy.  Tasks, git and other aspects of the system could never work with a system level proxy since we need to pass around an explicit proxy configuration.  We pass it down to git config, make it available to node task libs, etc...  We also need a consistent xplat model.  If you go back to earlier 2.x agents, they correctly didn't respect system level proxies.  The issue was when we adopted a new version of the core CLR, it required an explicit setting to not use the system proxy where that wasn't required previously.  So, portions of the system appeared to worked with the system proxy.  We fixed that bug and explicitly disabled the system level proxy.

**Comment by omeshp** [comment]
Thanks @bryanmacfarlane for the update, adding @tstooke who is the customer facing this issue while upgrade so that they can unblock themselves by using agent proxy.

**Comment by tstooke** [comment]
Thank you so much for investigating this!  When we initially configured our first agents, a consultant had indicated that the system-level proxy was the only way.  I've just set up a new Agent using version 2.126.0 and the .proxy file.  With this Agent, I ran a test Release that just downloads artifacts using the new Download Artifacts Task (0.127.7).  It all worked perfectly!

We will be configuring all of our Agents with the .proxy file so that we can update to the latest version.

**Comment by bryanmacfarlane** [comment]
@tstooke - Thanks for confirming!

**Comment by omeshp** [comment]
Hi, @tstooke Just to confirm, I thought you were using NTLM authentication for proxy which isn't supported in current "Download Build Artifacts" task. Are you using some other type of authentication for proxy?

**Comment by tstooke** [comment]
@omeshp It turns out that the proxy has no special authentication required.  The Agents run as domain accounts, and that's good enough.  I believe the proxy is configured to allow traffic based on source IP, so our server is allowed to use the proxy regardless of the current account.

We do have a few other Agents that are not under my control that have not been switched to per-Agent proxy, so we're not ready to re-enable the Download Build Artifacts task for the entire account yet.  I will let you know here or in an email separately.
