### ISSUE TITLE
Azure Container Registry artifact versions are in random order

### ISSUE THREAD

**Issue by ppanyukov** [Microsoft/vsts-agent#1386]
I'm not 100% sure this is the right place to raise this. If not could someone please direct me, that would be great. This directly affects our operations with VSTS though, so we'd ceratainly like to get this fixed in VSTS (don't care too much for Azure Portal).

## VSTS type and version
VisualStudio.com

## What's not working?

We have our Release Definition, and ther we have artifact coming from Azure Container Registry.

We have the release to run on a scheduled basis (say once an hour).

We notice that we recieve a completely *random* version of artifact from ACR on each scheduled run. 

See screenshot:

<img width="722" alt="screen shot 2018-01-29 at 10 21 57" src="https://user-images.githubusercontent.com/300031/35505556-574b1e36-04de-11e8-9477-80afbf059d1d.png">

--------

We also notice that when we create the release manually, the list of artifacts versions in the dropdown is also completely random. See the series of screenshots.

<img width="557" alt="screen shot 2018-01-26 at 23 00 34" src="https://user-images.githubusercontent.com/300031/35505721-e596840a-04de-11e8-9722-dc79902b1b3d.png">

<img width="626" alt="screen shot 2018-01-26 at 23 00 54" src="https://user-images.githubusercontent.com/300031/35505728-ebe21054-04de-11e8-9b1a-94ccd1135a37.png">

<img width="441" alt="screen shot 2018-01-29 at 10 26 24" src="https://user-images.githubusercontent.com/300031/35505733-f1b38cce-04de-11e8-9257-2e65388bc1d4.png">

--------

And, we also notice that when browsing ACR in Azure Portal, the tags are also shown in a completely *random* order.  See the series of screenshots.

<img width="597" alt="screen shot 2018-01-26 at 23 03 19" src="https://user-images.githubusercontent.com/300031/35506113-28c0fb4c-04e0-11e8-8281-a42cac8a8187.png">

<img width="598" alt="screen shot 2018-01-26 at 23 03 32" src="https://user-images.githubusercontent.com/300031/35506123-2d2a30ea-04e0-11e8-9a8c-059c6ea17c54.png">

<img width="600" alt="screen shot 2018-01-26 at 23 02 43" src="https://user-images.githubusercontent.com/300031/35506134-3604d1c0-04e0-11e8-9ba9-7ca717f5c1b0.png">

-----

The documentation at https://docs.microsoft.com/en-gb/vsts/build-release/concepts/definitions/release/artifacts#sources says:

> By default, a release created from the release definition will use the latest version of the artifacts. 

-----

What we'd like is:

- ACR artifacts are listed in "latest first" order in the dropdown when releases are created manually.

- For scheduled releases, the latest version is the one that runs.

- When listing tags in ACR in Azure Portal, they are listed in "latest first" order.

In any case, *some* stable ordering would be appreciated at the very minimum.

**Comment by TingluoHuang** [comment]
@GitHubSriramB Can you help customer with this?
@ppanyukov i think https://developercommunity.visualstudio.com/spaces/21/index.html is the official place to report this kind of issues. :D

**Comment by GitHubSriramB** [comment]
@ppanyukov - We will investigate this issue.

**Comment by FBNitro** [comment]
(subscribed) This is also affecting my project.  The "What we would like" above also satisfies my concerns.

**Comment by jikuma** [comment]
@ppanyukov We are working on this. Can you please help me understand your scenario better. Why are you using schedule release? Is the purpose of it is testing, in that case, I will suggest you to use continuous deployment (auto trigger) instead of schedule release. If the purpose is to do update your deployment automatically without manual intervention, you can use continuous deployment. I understand that for manual release the list tag dropdown is not ordered, and hence you will need to know the exact tag name which you want to deploy. Is it a blocker for you? Let me know if I am wrong.

**Comment by FBNitro** [comment]
Yes, this is a blocker.  

We have 20+ artifacts on the release job, if any one of them changes VSTS will trigger a release.  If we DO NOT change the ACR artifact (ie: I change some library elsewhere), VSTS does not select the most recently built version, instead it picks a random version in the list.  The version it picks happens to also be the one at the top in the UI if you were to attempt a manual build.

A Dated sort order needs to be applied so that the Release job will pick up the latest, instead of some 'random' image.

**Comment by SteveLasker** [comment]
Hi @jikuma 
We are working to add more rich meta-data to registry images. Including the last push date, last tag date, as well as other features like policy to delete images that were built, but not deployed, but keep images that have a policy of "release" for a pre-determined period of time. 
To help us understand your need:
Is this a production release? Generally, grabbing the latest, by build version could generate questionable results, depending on what you're looking to achieve. There are patterns for pulling the latest, by tagging an image with a stable tag. For instance, you could use ":latest" or a specific version ":v1" for instance. 
However, this doesn't mean the latest is actually any good. The build could fail, the build could succeed, but doesn't pass tests. 
A more stable means is to uniquely tag each build and save the last tested/known good image:tag. On subsequent deployments, you deploy that last known image. 
So, understanding the intent would help us answer your question, and get you the features you're looking for.
Steve

**Comment by FBNitro** [comment]
Hi @SteveLasker 
Our release job in VSTS handles our versioning for us.  So we have a large chain setup that does integration, integrationTesting, staging, stagingTesting, preprod, preprod testing, then we approve pushes off to production manually when we're happy with a release, which continues the pipeline. 

Having it grab the latest version at release time, and then tagging that version number at as part of that release, similar to how the rest of the VSTS artifacts work would be completely acceptable for our usage.

Currently, you build some (non-ACR related) code, it creates a new build version 1.2.3 and gets tagged as the latest within VSTS 'at that time', then that version # gets put into the release as an artifact, bound to build version 1.2.3 forever, the 'latest' tag is no longer relevant once the release task is created.  The release will always use version 1.2.3.  For me as a user, in the Artifact for the Release in VSTS, I say I want 'latest' (image below).  So it's latest at the time of the Release, it is not latest that is changing due to other builds etc.  Image:
![buildartifact](https://user-images.githubusercontent.com/9012961/36548835-1d17fc36-17a6-11e8-9254-b555879e62ce.png)


When we write to ACR we version all the releases (ex 0.1.45-1.0.27).  I would like to be able to do the exact same thing as what we do for the other build artifacts.  I want to say 'latest' in the artifact definition and have it grab the latest version (not 'latest' tag) and permanently associate that version with the release job.  I would be okay if it used the Date it was written to the ACR to figure out the latest version (at that time), or if it looked for the highest version # etc, or even the last version that was released (unless the ACR triggered the release)... 

I could find a use for tagging ACR entries as 'released' or not, as long as I could do that from within the release once it gets to a certain stage, because for us 'every' ACR version will be released in some way or another, it's just a matter of how far it gets down the chain.  If I could tag what stage of the pipeline, or the release version#'s associated with the Container entry that might be useful.

But short term, immediate need is having it get the 'latest' (most recent, not the tag) version at release time, without that I'm in trouble (current situation).

**Comment by SteveLasker** [comment]
Thanks @FBNitro 
First, thanks for the detail. This really does help. We are working to get the ordering fixed, so bear with us while this gets fixed, tested and rolled out. Since ACR is in all public Azure regions, (~27 I believe) with sovereign clouds coming, it will take a bit. 
In the meantime, I've been trying to get a blog post about this complete, so I'll work on it today. 
What you're trying to do, uniquely tag an image, so you know exactly which image will be deployed, and re-pulled if a node fails, is the best practice for released software. Stable tags are great for base images. Blog post coming. 
What I'm reading and seeing is the VSTS portal, querying ACR, isn't ordering the image:tags in a newest to oldest ordering. You're looking to simply grab the top in the list as the latest you want to deploy. 
We will fix this, just to be clear.
But, what happens if someone else checks in some code, or a base image update triggers a build (post coming :)), will the newest tag really be the one you deploy? 
While I appreciate the solution is manual today, would a solution that helps you understand the newest tag that past a certain test be more helpful? What if your test pipeline saved the newest tag that past whatever testing you want? You could then use that variable. Or, could copy/paste it in. 
Or, what if you could click a particular build, and say, [deploy this]. 
I'll get the post out, link it here when done, and see if that helps with more of the thinking around this. 
Steve

**Comment by FBNitro** [comment]
Every release we do is auto-triggered.  We rarely (2% of the time) ever manually perform releases, we have a large number of devs and if there's a change it is auto built and deployed immediately. If it fails, it's on the devs to fix, after which it will be deployed again.  So yes, in my current scenario, the most recent version at release time is assumed to be correct.

**Comment by SteveLasker** [comment]
Great. So, do you stash off that release number? if it's automated, can you pull that release number and use it for deployment? What I'm seeing in the post is the UI (and the underlying API), used by humans, is flawed. I get that from a troubleshooting point, it's more difficult. (fix in progress). But, how would the ordering of the list fix the underlying automation?

**Comment by FBNitro** [comment]
The ordering in the UI won't fix the issue.  My note here would:

> When we write to ACR we version all the releases (ex 0.1.45-1.0.27). I would like to be able to do the exact same thing as what we do for the other build artifacts. I want to say 'latest' in the artifact definition and have it grab the latest version (not 'latest' tag) and permanently associate that version with the release job. I would be okay if it used the Date it was written to the ACR to figure out the latest version (at that time), or if it looked for the highest version # etc, or even the last version that was released (unless the ACR triggered the release)...

**Comment by SteveLasker** [comment]
Ok, this makes sense. So, it's not the ordering in the API. You want the "newest" - latest is too overloaded. Newest, or even a stable tag will cause instability in your deployment. You want to deploy a very specific tag. You want VSTS to figure out what the newest version of that tag at the time you deploy. The deployment artifact would have 0.1.45-1.0.27. If the cluster needs to re-pull that image, it would pull that specific tag, and not the "newest" at the time it needs to pull an image. 
While I completely understand the request, and your workflow may have the rigor to keep other builds from getting in, and our tools should enable your team to implement this pattern, even if you want a test environment to always run the newest image in a test environment, I am concerned about other "newer" builds getting in between the time you build, test and release. Since you appear to be blocked, and it will be some number of days or week or so for us to get this fix out, can you hand off the number between test and release?  Actually, the fix will be longer as we need to order the tags in our ACR APIs, but VSTS will need a means to get the top 1 tag, ordered by last push, or possibly last tag date.

**Comment by ppanyukov** [comment]
@jikuma Additional info as requested.

We sometimes use VSTS and release definitions as a glorified cron to run jobs. For some of these, the "jobs" are packaged into docker containers and pushed to ACR.  The release definitions pull these images and run whatever they have in them.

We were hoping to have ACR as the artifact source for these release definitions, with semantics similar to how builds get the sources -- ability to get the last/newest pushed image, or specific tag. Or "newest" according to some sort order (if tags are sortable).

This is where we discovered that these scheduled release definitons receive completely random tags when they run.

We worked around this by just using "latest" tag and hardcoding this.  Which works, but we lose the taceability because of this.

Hope this helps understand our scenario?

**Comment by SteveLasker** [comment]
Hi @ppanyukov 
This is an evolving space, and there are lots of ways to use things. To try and put some context on tagging, we've finally pushed out this post on image tagging. Hope it helps and always interested in the feedback:  https://blogs.msdn.microsoft.com/stevelasker/2018/03/01/best-practices-for-tagging-and-versioning-docker-images/

**Comment by TingluoHuang** [comment]
i am going to close this issue since it's not really an agent related issue.
