### ISSUE TITLE
Custom Task Execution on Node.JS from Path instead of /externals/

### ISSUE THREAD

**Issue by MCollins434** [Microsoft/vsts-agent#1410]
## Agent version and platform
Agent version: 2.114.0
OS:  Windows Server 2012 R2

## VSTS type and version
On-Prem TFS
2017 Update 1

## What's not working?
We are creating custom release tasks using Node.JS

We have installed a more recent version on Node.JS on the Agent Server and added it to the Path.
When running the "npm" task in our build definitions, that is the version used, as expected.

The issue is when the Agent on that same server is later running the custom release task, the Agent is not looking in the Path to see if there is another node instance installed, it is _always_ using the node instance found in the /externals/node folder.

![Custom Task Execution](https://user-images.githubusercontent.com/6912375/36120545-70dfabc4-103b-11e8-929e-1de046453864.PNG)

**Is it possible to force the Agent to use the node instance found in the path to execute our custom tasks?**

**Comment by bryanmacfarlane** [comment]
That's by design.

There's two decoupled concepts:
1.  node/npm tasks which run the npm installed on the box (or in the task)
2. node as a javascript engine to run tasks.

Since task authors release tasks to the market place we need to guarentee which version of node is the javascript runtime (and it's the node 6 LTS path with 5.1 was part of at that time).

Your task in the market place can't run differently due to the environment of the machine of who consumes your extension.

Our agent has a concept of handlers and in your task.json when you say "node" that's node 6.x LTS.

So, the npm task uses the embedded node 6.x version to run the task script and that task script will 'which' npm and run that from your path.

**Comment by MCollins434** [comment]
Understood. That all makes sense.
Thanks a lot for the quick response!

**Comment by bryanmacfarlane** [comment]
np - this was one of the things that even confused us in the early days of design :)
