### ISSUE TITLE
Add a setting to name build definition in .vsts-ci.yml

### ISSUE THREAD

**Issue by TerrapinStation** [Microsoft/vsts-agent#1418]
It would be nice to be able to name these definitions within the yml file instead of being limited to the default (<REPO_NAME>/<REPO_NAME> CI)

**Comment by ericsciple** [comment]
@TerrapinStation We are planning to have a folder layout convention for multiple definitions. Something like
```
.vsts-ci/
    definitions/
        my-fancy-definition.yml
        my-other-definition.yml
```

So in the above example, `.vsts-ci/definitions` is a specific folder that we watch on-push. If you add a yaml file to that folder, then we will create the definition if it doesn't exist and infer the definition name from the file name.

Will that work? Thoughts?

**Comment by TerrapinStation** [comment]
@ericsciple That would be perfect! It would also solve one of the other problems we have, which is managing multiple yml definitions in one repo.

**Comment by ericsciple** [comment]
Thanks for confirming.

Right now we are wrapping up CI triggers and we are hoping to complete yaml templates next (pull in separate files for reuse), and then probably templates from a separate repo. I would guess a specific folder layout would be sometime after that, but I don't know when. User voice sometimes also helps us prioritize features.

I'm going to go ahead and close this issue, since we typically don't track our backlog here. Although I do appreciate the feedback - and this repo has been useful for that.

I'll start a spec for the folder layout concept. We've started creating specs as PRs into the docs that live in this repo, so that we can discuss in the open and get feedback. I'll start a PR (i.e. spec) for the folder layout

**Comment by ericsciple** [comment]
linking to PR https://github.com/Microsoft/vsts-agent/pull/1430

**Comment by ggirard07** [comment]
Any update on that?
We moved to yaml a few weeks ago but we now need to support 2 build definitions on the same repo

**Comment by venura9** [comment]
this is starting to become a problem now.

**Comment by AndyLysenko** [comment]
Any updates? When is it expected?
