### ISSUE TITLE
Add Basic Auth option

### ISSUE THREAD

**Issue by bryanmacfarlane** [Microsoft/vsts-agent#152]

**Comment by bryanmacfarlane** [comment]
not going to support alt creds.  use PAT

**Comment by LarryRothOakton** [comment]
Using PATs means that all our build agents are ticking time bombs which are going to break in 12 months time. Working in a consulting environment makes this extremely challenging because we configure agents for our customers and may not be engaged with the customer at a later period. How can I ensure that our service accounts do not magically stop working? Or am I misunderstanding something here?

**Comment by bryanmacfarlane** [comment]
@LarryRothOakton - the PAT is only used at config time to register the agent.  It's not persisted.  Technically, it could be one time use only**.  It registers the agent with the PAT and the server generates a signed jwt token which is encrypted and used to listen to the queue.  Messages are sent to the agent per build which contains a per build time bombed jwt token for the life of that build.

So, no, it's not a ticking time bomb and it's secure.

**Comment by bryanmacfarlane** [comment]
The reason I put a ** is because of this robust and secure approach (where token is not persisted or used), when you unregister the agent, it prompts you again for a PAT token (only downside).  You can use it, acquire another or simply wack the agent folder and delete from web UI if easier.

**Comment by LarryRothOakton** [comment]
@bryanmacfarlane - Thanks for the quick response and thanks for clearing up my confusion. Great approach which provides good security. Happy with that and the whole VSTS build engine in general. Really excellent build platform!

**Comment by bryanmacfarlane** [comment]
Great.  We need to doc the whole exchange.  Hopefully soon.  Thx
