### ISSUE TITLE
Git rid of MD5

### ISSUE THREAD

**Issue by ericsciple** [Microsoft/vsts-agent#183]
or relegate it to a best effort fallback.

We only use it for hashing a name or path today... so isn't a security issue... don't have the details offhand.

**Comment by bryanmacfarlane** [comment]
Dupe of https://github.com/Microsoft/vsts-agent/issues/182

**Comment by jeaster1** [comment]
I would like to reopen this.  I have FIPS installed on a server machine set by a Group Policy which I don't have access to shut off.  Because MD5 is a bad cipher to use, it fails FIPS and then I can't install VSTS on the server (agent) that I'm using.

**Comment by ericsciple** [comment]
@jeaster1 which agent version are you using?

**Comment by ericsciple** [comment]
also are you on VSTS or TFS? If TFS, which version.

**Comment by jeaster1** [comment]
Just thought about this, I apologize.  Since we are using TFS 2015 (on prem), I was using the shipped version that comes with 2015 (and of course it wouldn't have your updates).  I'm wondering now if anyone has tested VSTS Agent with 2015 on prem and whether or not it works?  I'm working on downloading it now and hopefully have that tested within 1-2 hours.

**Comment by TingluoHuang** [comment]
@jeaster1 the latest version agent has drop the support for TFS2015, but you can try old release, like https://github.com/Microsoft/vsts-agent/releases/tag/v2.112.0

**Comment by ericsciple** [comment]
@jeaster1 the v2 agent is not supported with TFS 2015. although technically 112 will connect is was never meant to work. you should not use it.
