### ISSUE TITLE
Question: why do we need sudo in config.sh?

### ISSUE THREAD

**Issue by ppanyukov** [Microsoft/vsts-agent#277]
in `config.sh` we see we configure the agent with `sudo`.

```
if [[ "$1" == "remove" ]]; then
    sudo ./bin/Agent.Listener unconfigure
else
    # user_name=`id -nu $user_id`

    sudo ./bin/Agent.Listener configure $*
fi
```

What is the reason for this?

**Comment by bryanmacfarlane** [comment]
Because if you answer Y to configure as a service later, you will need to have already elevated.  By the time the C# code runs the script it's too late to elevate.

We have considered splitting configure the agent and generating the service file (plist on OSX and systemd file on unix) into two steps.

**Comment by bryanmacfarlane** [comment]
It's also important to note that before it does that, it snapshots your path into .path and key env vars into .env so when the service (launchagent or systemd) runs, it can set that up so it just works when running as a service and provides a unified way of resnappshotting those (with user having to manually modify plist or systemd files).

That part needs to be done before you elevate so you can capture their environment.

**Comment by bryanmacfarlane** [comment]
I just committed changes that splits config agent and config as a svc for nix.  So config agent doesn't need sudo.

Look for preview very soon and I'll update docs when it drops
