### ISSUE TITLE
Add support for shallow git clone

### ISSUE THREAD

**Issue by 501st-alpha1** [Microsoft/vsts-agent#278]
I'm currently looking for ways to speed up my VSTS builds. I have noticed that the "Get sources" step takes almost 3 minutes to run, because it does a full `git clone` of the repo.

My first idea was to cache the repo on the agents, and do a `pull` to update the repo when needed. However, [this StackOverflow comment](//stackoverflow.com/questions/31824365/caching-nuget-packages-on-vsos-host-agent-pool/31826695#comment51587812_31826695) indicates that hosted agents are assigned at random, so nothing can be cached on them across builds.

My next idea was to do e.g. `git clone --depth 1`, so that only the latest commit is fetched.

From what I can tell (looking at the source [here](//github.com/Microsoft/vsts-agent/blob/master/src/Agent.Worker/Build/GitSourceProvider.cs) and [here](//github.com/Microsoft/vsts-agent/blob/master/src/Agent.Worker/Build/GitCommandManager.cs#L141)), there isn't currently an option to do this.

Is this something you would be open to adding support for? If so, I am interested in submitting a PR for this.

**Comment by bryanmacfarlane** [comment]
This agent doesn't do a full clone everytime.  It will re-use the repo and fetch.  It's only the initial clone.

The issue is if you're using the hosted pool, it re-images the machines between builds so every build is the first time.  If you deploy your own VM/machine with this agent, your will get incremental fetch and possibly even incremental build.

That all said, we will add shallow clone.   The first step was for this new agent (this repo) which is in preview to use git.exe instead of libgit.  That allows us to support a myriad of git options which weren't all supported by libgit.

**Comment by 501st-alpha1** [comment]
Okay, thanks for the info.

Yeah, I figured I could switch to my own VM, but that's one more thing I'll have to manage, so I'm trying to avoid that if possible.

Great! To clarify: is someone already working on this, or would you like me to work on a PR?

**Comment by bryanmacfarlane** [comment]
We need service side support for it (check box on repo tab, sends in job message, etc...) - it's on our backlog.  First step is this agent will start getting used in hosted build in a sprint or two then we can add ...

**Comment by 501st-alpha1** [comment]
Okay. Let me know if/when there's anything I can do to help with this.

**Comment by TingluoHuang** [comment]
#620
