### ISSUE TITLE
Question: Build agent hook for completed build

### ISSUE THREAD

**Issue by claudiospizzi** [Microsoft/vsts-agent#393]
Is it possible to run custom code or as script, like from a hook, if the build agent has completed a build?

It should run as soon as the build has been completed and committed to TFS but before a new build from the queue is accepted, to do some cleanup work on the build server or save away the state.

**Comment by TingluoHuang** [comment]
@claudiospizzi You can add an always run step to the end of the build definition, let it do the cleanup or same state, will this help with your scenario?

**Comment by claudiospizzi** [comment]
@TingluoHuang Not really, because we currently have hundreds of XAML build definitions, which should be replaced in the future with the new build system. To maintain and check 1000+ XAML build definitions, if each author has added one specific last task as a last always run task, is not really suitable. It would be great if this can be executed as post build task on the build agent. Use case is to save the state and clean up the state of the whole build agent.

**Comment by bryanmacfarlane** [comment]
We have a feature for process inheritance coming at some point.  However we implement, it will be a task (even if defined a project, pool, agent level and appended dynamically).  Tasks are the agent extensibility mechanism.  With the new build the goal is to push as much as we can to the server (workflow etc...) and keep the agent as simple as possible - it knows how to run a sequence of steps.

On a side note, typically the number of definitions goes way down in the new build system, since you can define multiple trigger and branch/path rules on the same definition.

I'll add this note to our process inheritance work.  It's not agent work since it won't be an agent plugin.

**Comment by claudiospizzi** [comment]
@TingluoHuang @bryanmacfarlane 

I have to come back to this question. Maybe, I can give you more details on why we need a hook for completed builds (aka pre- /post-build event) on the build agent and how we plan to use it.

The core idea is, that we can combine the new TFS build agent with Windows Server Containers available in Windows Server 2016. The goal we try to reach is, having a clean bulid environment (a clean new container) for each running build.

We've set up the build agent within a container and now the plan is, that after each build, the container should shutdown. With a hook on the build agent, we are able to achieve this. You can see, why a build task is not situable - this has to happen as soon as the build has completed, not as last step of the build itself.

After the build agent has shutdown the parent container, a service running on the container host will export or delete the container. Afterwards, it will create a new container based on the container image and start it. Within the image, the build agent is already configured to connect to TFS. As soon as the container is started, the build agent is abailable for the next build.

Of course I will be fine, if you can implement a post-build tasks which is running after the build but configured on the server and not as part of the build itself.

I hope I could convince you for a new pre-/post-build event or task.
