### ISSUE TITLE
Clarify run as a service option in config is windows only

### ISSUE THREAD

**Issue by ezeeetm** [Microsoft/vsts-agent#394]
Code snippet here:

https://github.com/Microsoft/vsts-agent/blob/master/docs/start/configvsts.md#configure

States that the following prompt should appear at the end of the intial ./config.sh run:

    Enter run agent as service? (Y/N) (press enter for N) >

However, this is not the case.  Actual output (on Ubuntu 16.04 LTS) is (last 2-3 lines are the interesting ones, the rest included for completeness):

```
ubuntu@ip-172-31-32-146:~/myagent$ ./config.sh

>> End User License Agreements:

Building sources from a TFVC repository requires accepting the Team Explorer Everywhere End User License Agreement. This step is not required for building sources from Git repositories.

A copy of the Team Explorer Everywhere license agreement can be found at:
  /home/ubuntu/myagent/externals/tee/license.html

Enter accept the Team Explorer Everywhere license agreement now? (Y/N) (press enter for N) > Y

>> Connect:

Enter server URL > https://redacted.visualstudio.com
Enter authentication type (press enter for PAT) >
Enter personal access token > ****************************************************
Connecting to server ...

>> Register Agent:

Enter agent pool (press enter for default) >
Enter agent name (press enter for ip-172-31-32-146) > linuxAgentPoC
Scanning for tool capabilities.
Connecting to the server.
Successfully added the agent
Testing agent connection.
Enter work folder (press enter for _work) >
2016-07-13 19:56:14Z: Settings Saved.
ubuntu@ip-172-31-32-146:~/myagent$
```

As you can see, it does not prompt to run Agent as a service.  Was this option removed?

doing 

    sudo ./svc.sh install
    sudo ./svc.sh start

seems to work after running config.sh...but the docs should be updated to reflect the manual installation of the service is required, and not to expect the prompt at the end of config.sh

**Comment by ezeeetm** [comment]
i can do a PR for this to fix this minor thing if someone can confirm that its incorrect?

**Comment by bryanmacfarlane** [comment]
It only does that on windows.

If you go through the start ubuntu docs, you'll see at the bottom the last step has a link to run as a service:  https://github.com/Microsoft/vsts-agent/blob/master/docs/start/svcsystemd.md

For nix, we used to offer that option but removed and made it two step per this issue: https://github.com/Microsoft/vsts-agent/issues/277

The problem is we would require sudo up front because you *might* answer yes to that question later.  Some nix shops weren't allowed to sudo and they ran interactively.  So, for nix, it's two steps, `config.sh`, run `svc.sh install` if you want us to generate a systemd service for you.

I'll add a note on that page.  I'm trying to avoid duplicating that doc because of the one difference.

**Comment by bryanmacfarlane** [comment]
done
