### ISSUE TITLE
OnPrem TFS2015.Update3 with Windows Agent not supported (yet)

### ISSUE THREAD

**Issue by RobertK66** [Microsoft/vsts-agent#404]
Agent version and platform:  2.103.0
OS of the machine running the agent:  Windows10
VSTS type and version:  On-Prem TFS 2015 Version 14.102.25423.0 (aka Tfs2015.Update3)

**Pls. make clear in your documentation (on starting page) that this setting is not supported yet !**

Same as @SDxKeeper here: #366 I completely misunderstood  the line 
> TFS.vNext (onprem) Yes Yes

I tried to switch my vNext builds to the new agent in order to test my own custom TFS extensions and hit the same problem(#366) as @SDxKeeper.
Unfortunately it looks that I have to wait for  TFS 2016 RTM for that scenario.....

But a clearer statement on your supported version table would have spared me some time. So if you mean  "TFS 2016 RTM" than please write  "TFS 2016 RTM" iso TFS.vNext. Thx.!

**Comment by bryanmacfarlane** [comment]
It's already on the front page one row below the one you pointed out

>> TFS2015 (onprem)	Yes	No	Windows use agent with 2015

**Comment by bryanmacfarlane** [comment]
It's unclear why you can't use the agent provided with TFS 2015 to test your extension.  You can use the hosted pool or deploy [your own agent from the TFS 2015 server](https://www.visualstudio.com/en-us/docs/build/agents/windows).

**Comment by RobertK66** [comment]
No prob here with testing on TFS2015. I only wanted to be up to date with my tests and once the new build agent arrives I plan to rewrite my build steps to work without ps scripts and therefore on all platforms. I simply misread your docu after last release and as I was not the only one I wanted to give feedback about it ;-).

**Comment by bryanmacfarlane** [comment]
https://github.com/Microsoft/vsts-task-lib/blob/master/node/docs/stepbystep.md

**Comment by StingyJack** [comment]
> It's already on the front page one row below the one you pointed out

I have a 2015 on prem TFS server - can I update the build agent I have with this one, or not? I should be able to know from quickly looking at the chart and not diving through pages of docs.

MS should really reconsider giving priority support to competing products (Maven over PowershellGet Repo, Git over Tfvc, OsX/*nix over windows). Some of us don't want to deal with Java/Ec;lipse, easy to be dangerous version control systems, or do everything via command line - which is why we are using your products.

**Comment by bryanmacfarlane** [comment]
@StingyJack - The front page makes it clear you cannot.

The policy is equal footing for all platforms.  The 2.x agent actually works works on TFS2015.3 - the issue isn't the agent.  The issue is the all the tasks had powershell implementations for windows support which relied on coupling with the 1.x agent (loaded .net desktop binaries in proc and this is a cross platform net core).  

So you can configure this agent (we did all the work so it will work with 2015) but it's the tasks in the marketplace that were coded with the powershell in proc handler that won't work.  All the tasks in 2015 and the marketplace tasks that targetted 2015 rely on a tight coupling.  So effectively you can't realize this new arch and agent against 2015.

The reason it works for *nix is a it just so happens all the xplat tasks were written with typescript and those we're encapsulated and out of proc to start with.  The new properly architected agent follows the decouple arch of the deprecated vso agent: https://github.com/Microsoft/vso-agent

https://github.com/Microsoft/vsts-task-lib
