### ISSUE TITLE
Removal of bundled git in 2.103.1 makes life very hard, especially on RedHat/Centos

### ISSUE THREAD

**Issue by ppanyukov** [Microsoft/vsts-agent#419]
## **Agent version and platform**
v2.103.1
<br>
Linux, Centos 7
<br>

## **What's not working?** 

Release `v2.103.0` had `git` bundled with it. Which was great since the bundled version was the one that actually worked with visualstudio.com. This was very nice and made the agent installation easy and friendly for all environments.

Now release `v2.103.1` no longer ships with bundled git.  Instead it states `git >= 2.9.0` is a system pre-req.

There are several problems with this:

- On any official Centos installation the latest packaged `git` is `1.8.3.1`, even with EPEL repo.

- The docs here suggest to build git from source on Centos -- this greatly complicates things. It is certainly way more complicated than using bundled git.  In scenarios where the agent runs in containers building from source complicates things even more.

- Are we sure we must have the cutting edge release `2.9.0`? It's only been out a month since June 10. Even on latest Ubuntu and Debian git is way behind this if you only use official repositories (Debian 8: 2.1.4; Ubuntu: 2.7.4).

If there are special git requirements for VSTS agent / visualstudioonline.com which require a lot of work, then it certainly makes sense to bundle it.  It would be very nice if bundling was reinstated.

If I could propose the following:

- For any supported platform, if git of required minimal version cannot be obtained from the official repos, bundle it with the VSTS release package. Basically don't make people build from source or obtain binaries from non-official repositories (because latter can be banned in many places).

**Comment by bryanmacfarlane** [comment]
We added back compat code where if we're working with VSTS then it will only demand git 2.0 and we put user/pass in the url and it works.

If you're working against on-prem then yes, we absolutely need 2.9.  The official 'mechanism' since we want to remove the multiple back compat mechanisms is 2.9.

Git 2.9 has the ability to add extra header and we use it to pass the bearer token.  In on-prem (TFS.vNext) it is the only way to get through the IIS challenge front door.  We want one mechanism and one code path to support.

We (Microsoft) had changes into git core in 2.9 to support this.

We are not going to bundle because there is no portable git to bundle with our agent (like there is on windows).  Git simply does not produce a portable xcopy build for Linux.  If you find one, we would be happy to bundle it.  We don't want to be responsible for building and distributing git distros on linux.  We did it while in preview while we waited for it to show up in homebrew and other apt-get and rpm feeds

I added docs for the few cmd lines to get it.

**Comment by ppanyukov** [comment]
OK, understandable, even if still makes it way more difficult to deploy the agent than before. Portable xcopy git -- we may be out of luck there but I will keep an eye on such a thing.

Meanwhile, for those who find it a pain to build from source, I have a repo which makes it super easy to do so on any machine for Centos (and easy to add pretty much any other Linux distro).  There are currently also pre-built binaries of `2.9.0` for Centos 5, 6, and 7. 

Might be helpful, see: https://github.com/ppanyukov/git-build

**Comment by bryanmacfarlane** [comment]
Cool.  Thanks
