### ISSUE TITLE
Cmd and AzurePS capabilities are not available in vsts-agent for Mac

### ISSUE THREAD

**Issue by james-hu** [Microsoft/vsts-agent#457]
## **Agent version and platform**
Version of your agent? 2.103.1
<br>
OS of the machine running the agent? OSX 10.11.6
<br>
## **VSTS type and version**
VisualStudio.com
<br>
If VisualStudio.com, what is your account name? http://rtstatistics.visualstudio.com
<br>
## **What's not working?** 
Cmd and AzurePS capabilities are not available.
In Control Panel -> Agent Pools, I cannot find them on the capability list, and my build job couldn't start.

Below are the messages:
```
No agent found in pool Default which satisfies the specified demands:
Cmd
maven
maven
Cmd
azureps
Cmd
Agent.Version -gtVersion 1.102.0
```

Is there any way to add these two capabilities on Mac? Or is it just impossible at this moment? Are they on roadmap?

<br>

**Comment by bryanmacfarlane** [comment]
By design:
Mac does not have a cmd shell.  Use shellscript task
azureps runs azure powershell cmdlet which are windows only

maven capability is registered if maven is installed on the box and the M2_HOME envvar var was available (maven can be found) when configuring.   If you run as you (interactively) make sure it can be found.  If running as a service details are [here](https://github.com/Microsoft/vsts-agent/blob/master/docs/start/svcosx.md)
