### ISSUE TITLE
agent.buildDirectory variable doesnt work with this agent

### ISSUE THREAD

**Issue by AshwiniChalla** [Microsoft/vsts-agent#49]
agent.buildDirectory returns undefined

**Comment by bryanmacfarlane** [comment]
It's set on ~line 152 in https://github.com/Microsoft/vsts-agent/blob/ae5141fa424b6a8cdbbc5dc1b16d3669221e7aee/src/Agent.Worker/Build/BuildJobExtension.cs 

I'll need details on what's not working and you're repo.  I see it being set.

**Comment by bryanmacfarlane** [comment]
re-open if you have the details I asked for above.  I believe it's being set.

**Comment by AshwiniChalla** [comment]
With this agent getVariable of vsts-task-lib doesnt work.
[ https://github.com/Microsoft/vsts-task-lib/blob/master/node/lib/task.ts](url)

**Comment by AshwiniChalla** [comment]
I guess the variable is set as environment variable previously.

**Comment by ericsciple** [comment]
I fixed a bug yesterday where the env var wasn't set properly. The lib is looking for it with "." replaced with "_", although the agent wasn't converting "." to "_" when setting the env vars. It's my fault, it's fixed now in master and I'm pretty sure it's the issue you're running into. I'll test later and confirm it's fixed in master when consuming from the lib.

**Comment by ericsciple** [comment]
Confirmed it's fixed in master.
