### ISSUE TITLE
GatedCheckIn does not work if one of the merged files 

### ISSUE THREAD

**Issue by thechrisjohnson** [Microsoft/vsts-agent#504]
By default, TFVC has certain file types that are considered "un-mergeable", and will take an exclusive lock on them anytime they're modified in a workspace.

In XAML build, we worked around this issue by always undoing all pending changes in the agent workspace after the build finished, but before we attempted to check-in the shelveset.

In the new agent, we're not undoing the pending changes to the agent workspace after the build succeeds, so the shelveset check-in will fail in this scenario.

**Comment by ericsciple** [comment]
workaround: [enable multiple checkout](http://dev.goshoom.net/en/2014/10/locking-in-team-foundation-version-control/)

**Comment by andrewtechhelp** [comment]
I'm having this issue too and in Team -> Team Project Settings -> Source Control I already have "Enable multiple check-out" ticked.

**Comment by ericsciple** [comment]
@andrewtechhelp have you tried enabling File Merging? See Team Project Collection -> Source Control

**Comment by andrewtechhelp** [comment]
I'll look into that. I'll have to note down how all the settings are so I can put them back after this is fixed.

**Comment by RadoslavGatev** [comment]
We experience the same issue. We use the v2.104.2 of the build agent. 
The shelveset check in just fails after a successful build due to a lock set on the binary files.

"Enable multiple check-out" is enabled.
"File Merging" is not enabled for binary files. And why it should be? As far as I know in normal circumstances(without any manual locks, with multiple check-out enabled) you should never run into such a problems when trying to check in from your local instance of Visual Studio.

**Comment by ericsciple** [comment]
We switched to local spaces which appears to fix this issue. Will be fixed in 2.105.2 released later today.

**Comment by ericsciple** [comment]
One thing to note: although this is fixed in [2.105.2](https://github.com/Microsoft/vsts-agent/releases/tag/v2.105.2) (switched to local workspace for new workspaces), the agent may still reuse a server workspace if one was created before. You may need to run one build with a variable `build.clean` set to `source` to force the workspace to be dropped and recreated as a local workspace.
