### ISSUE TITLE
Agent ships with NuGet 3.3.0 rather than latest version

### ISSUE THREAD

**Issue by oatsoda** [Microsoft/vsts-agent#582]
## **Agent version and platform**
2.105.5
Windows
<br>
## **VSTS type and version**
VisualStudio.com
<br>
## **What's not working?** 
This version (and by looking at the code future versions) of the agent are shipping with NuGet 3.3.0 which will not work with newer `netstandard` package resolution.  The workaround is to alter the vNext package installer step and hardcode a fixed path and install NuGet on the build server.

It would be preferable to ship the agent with the latest NuGet each time so that it is kept up-to-date.  

See https://github.com/Microsoft/vsts-agent/blob/3c6145febf80de375e103c2a247bec2d4b732802/src/Misc/externals.sh#L140

The URL could be altered to https://dist.nuget.org/win-x86-commandline/latest/nuget.exe

**Comment by bryanmacfarlane** [comment]
It was done explicitly because there were compat scenarios broken in the latest nuget.  The packaging / nuget teams are trying to get to one nuget version that works all versions.

We also have a tools feature where newer versions can be specified and pulled / cached on demand: https://github.com/Microsoft/vsts-tasks/blob/master/docs/tools.md

**Comment by bgever** [comment]
@bryanmacfarlane Please reopen this issue, since the bundled version 3.3.0 causes NuGet packages targeting .NET Standard to fail installing and causing our builds to fail. This is a problem!

How can we use that tools feature from the VSTS build config, if this is the workaround?

**Comment by bryanmacfarlane** [comment]
We can't open this issue and change to latest as that would fail other builds.  We were shipping latest for a short period and many more builds failed.

The issue isn't the agent.  The issue is we need one version of nuget that works for the various scenarios.  They are in the process of getting that.

The workaround is the nuget tasks have an input to specify the location of nuget to use.

I'll send this to the packaging and nuget team so they can follow up with you.

**Comment by oatsoda** [comment]
> We were shipping latest for a short period and many more builds failed.

@bryanmacfarlane Would any of these problems explain why I am having problems with Agent 2.105.1 NuGet 3.5.0? - see http://stackoverflow.com/questions/39352013/nuget-fails-to-restore-netstandard-libary-for-netstandard1-2-in-vnext-build-agen

**Comment by zjrunner** [comment]
Are you sure you have nuget 3.5?  That rtm hasn't been released yet but you mentioned getting it from an update (a preview maybe?).  

To answer the original question, we cannot force everyone on to a newer nuget.exe automatically.  After 3.3 there are some back compat breaks that impact a large number of users.  We tried moving forward twice and had to roll it back each time (to 3.4 and later to a beta 3.5).  Instead, we'll be releasing with 3.3 as the default for compat purposes, and the installer task will have a simple radio button to opt in to 3.5 (potentially an rc for some period of time) or your own custom version of nuget.exe as it does today.  We expect some users will still want their own nuget.exe version and we currently do not intend to release new options in lockstep with nuget.  

In the future we're looking at major versioning of tasks that would allow us to move forward with breaking changes, deprecate the old version, and give users a grace period to move forward safely/cleanly.

**Comment by bgever** [comment]
That sounds like a sensible approach @zjrunner, and important information that should have been mentioned when this issue was closed. The opt-in for 3.5 on the NuGet task will be much appreciated, something I hoped to see. Maybe another option could be 'Latest', using the official feed from NuGet to get the latest version.

Currently we have it working with 3.4.4 using the custom path, and that will do for us in the meantime.

**Comment by zjrunner** [comment]
For now I'm closing this issue since we are tracking the release with other bugs and issues.  Right now we are not planning a 'latest' only because of the uncertainty version changes have brought to our task in the past.  I'll record the request though and we can reconsider if we get enough people asking for this, willing to see those unexpected breaks when 'latest' changes, and have a good way of letting people understand risk of this option from within the UX.

**Comment by Javietto** [comment]
I don't understand how this is closed. If you're unwilling to use latests because of builds unexpectedly breaking then at least make it an option on UX because quite frankly the workaround for those of us who use netstandard implies adding an extra step to our build definitions and pretty much beats the interest of using a hosted agent.

**Comment by bryanmacfarlane** [comment]
They are doing that in the next sprints rollout

In parallel there is work to pull in JIT: https://github.com/Microsoft/vsts-tasks/blob/master/docs/tools.md

**Comment by zjrunner** [comment]
To be clear, the next sprint rollout has the newest nuget.exe (3.5) as an option, not a true 'latest' floating option.
https://github.com/Microsoft/vsts-tasks/pull/2540

**Comment by kfstorm** [comment]
Hi everyone, why I can see NuGet version option in NuGet installer and publisher tasks but not in packager task? I run into a problem that needs NuGet version 3.5 to generate a package.

**Comment by TingluoHuang** [comment]
@kfstorm this is the repo for agent, you need open an issue in the Task repo. https://github.com/microsoft/vsts-tasks

**Comment by kfstorm** [comment]
@TingluoHuang Thanks. I've found an existing issue for my ask: https://github.com/Microsoft/vsts-tasks/issues/3636
