### ISSUE TITLE
[Request] - Allow to join Azure disk and use as work directory for Hosted Agent

### ISSUE THREAD

**Issue by chrisaut** [Microsoft/vsts-agent#594]
A typical build for me looks like this:

![image](https://cloud.githubusercontent.com/assets/8252355/18509486/1cb4aa92-7aa3-11e6-8e90-aded5b956c32.png)
Notice by far the slowest activities are npm install and dotnet restore. Both of which need to run each time from scratch even if nothing changed (because on hosted you always start with an empty directory).

On a self hosted agent, the same build looks like this:
![image](https://cloud.githubusercontent.com/assets/8252355/18509494/252f2832-7aa3-11e6-906e-4ad7e60d66b3.png)

While I'm sure part of this is just the faster hardware, especially npm install and dotnet restore are much faster, because they don't have to start from scratch each time.

Wouldn't it be nice if we could somehow use a disk/storage whatever something that we pay for on Azure that the hosted agent can use? I don't want to maintain an Azure VM, but I'd gladly allocate some storage space that the hosted agents can use.

## **VSTS type and version**
VisualStudio.com

**Comment by bryanmacfarlane** [comment]
This is on our MMS (machine management service) backlog.  We also want support for your own private pool that we manage (point us at your subscription).  This offers incremental source, packaging, and custom control over toolsets used.

I'm closing since not really agent related but we are tracking toward this.  First up is some reliability and COGs work but then private pools is next.
