### ISSUE TITLE
Support .NET Core 1.0.1 on hosted agent

### ISSUE THREAD

**Issue by Peter-Juhasz** [Microsoft/vsts-agent#641]
## **Agent version and platform**
Version of your agent? 2.107.0
OS of the machine running the agent? Windows
## **VSTS type and version**
VisualStudio.com hosted agent
## **What's not working?** 
.NET Core 1.0.1 is not installed on hosted agents.
## **Agent and Worker's diag log**
2016-10-13T10:29:43.2530154Z ##[command]dotnet test
2016-10-13T10:29:43.8030163Z Project App.Web (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
2016-10-13T10:29:43.9310164Z Project App.Web.Tests (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
2016-10-13T10:29:43.9970161Z The specified framework 'Microsoft.NETCore.App', version '1.0.1' was not found.
2016-10-13T10:29:43.9970161Z   - Check application dependencies and target a framework version installed at:
2016-10-13T10:29:43.9970161Z       C:\Program Files\dotnet\shared\Microsoft.NETCore.App
2016-10-13T10:29:43.9970161Z   - The following versions are installed:
2016-10-13T10:29:43.9970161Z       1.0.0
2016-10-13T10:29:43.9970161Z       1.0.0-rc2-3002702
2016-10-13T10:29:43.9970161Z   - Alternatively, install the framework version '1.0.1'.
2016-10-13T10:29:43.9980162Z SUMMARY: Total: 1 targets, Passed: 0, Failed: 1.
2016-10-13T10:29:44.2581568Z ##[error]Process completed with exit code -2147450749.

And please follow Microsoft releases with a shorter time frame next time. .NET Core 1.0.1 was released already a month ago.

**Comment by TingluoHuang** [comment]
@Peter-Juhasz 
update software on hosted agent always takes long time, I would suggest take reference at #365, install dotnet core as part of your build.

**Comment by bryanmacfarlane** [comment]
@Peter-Juhasz - this also doesn't have anything to do with the agent itself (this repo).  The hosted image provides tools on the images as a convenience and as Ting pointed out, you can pull the version you specifically need at runtime during the build.

**Comment by Peter-Juhasz** [comment]
@bryanmacfarlane Okay, what is the right place to report issues like this one? I searched for "vsts" and this repo came up as the most relevant. I could even choose the Hosted Agent to report.

On the other hand, I don't think it could be a good practice to install tools so essential like .NET itself every single time you run a build. Then why is 1.0.0 installed? You could install that too. Or even Visual Studio 2015 for .NET builds... That's nonsense.

I think the solution would be better collaboration and schedule between the teams inside Microsoft. Technologies get updated as rapidly as every month and there is still no official support for .NET Core 1.0.0 other than "add command line steps"/"install it yourself"/.... I think it slows down the adoption and make you feel frustrated every time you want to keep your project up to date, but get stuck every time, because it is not supported even on VSTS and you have to rollback.

**Comment by bryanmacfarlane** [comment]
@Peter-Juhasz - if you have an agent that's persistent it doesn't install the tool every time.  If you install an agent on an azure VM, it will only pull the tool the first time you reference a new version.

We have a tool installers feature coming soon and node/npm and dotnet will be the first two:
https://github.com/Microsoft/vsts-tasks/blob/master/docs/tools.md  

The hosted pool is a convenience (easy to get going) but you lose (1) control of exactly what is pre-installed (2) persistent code, packages (npm, nuget) and tools (apt-get etc...) pulled at build time since the machine is re-images.  Having a private agent in a VM is less convenient but comes with more control and better incremental performance since nuget packages etc... won't get pulled every build.

Realize we can't pre-install every version of every tool on the image.  Of course Microsoft mainline will get pre-installed like this one.  But we wait for it to release and then there is some latency to it (we refresh the image every sprint or so).  So 1.0.1 will get updated and it will be on the image.  I was simply giving you an option in the interim.

Tasks repo would be a more appropriate place since agent isn't meant to carry all possible versions of all development tools - it's an engine.  https://github.com/Microsoft/vsts-tasks

The best place would actually be our hosted image code but that's closed source.
