### ISSUE TITLE
Unable to Label Sources using $(GitVersion.NuGetVersion), as it creates a tag with variable name, not value. 

### ISSUE THREAD

**Issue by JoeBrockhaus** [Microsoft/vsts-agent#716]
## **Agent version and platform**
2.109.1 - Windows
## **VSTS type**
http://mssc.visualstudio.com
## **What's not working?** 
Issue described here http://stackoverflow.com/questions/41026158/vsts-label-sources-with-gitversion-nugetversion-creates-tag-with-variable-nam

Instructions [here](https://www.visualstudio.com/en-us/docs/build/define/general#variables) indicate variables are usable in this field, but if those can never be runtime values, that defeats the purpose imo.

**Comment by ericsciple** [comment]
one way to do this would be to script git. instructions for enabling this and granting ACLs to the build identity can be found here: https://www.visualstudio.com/en-us/docs/build/scripts/git-commands#enable-scripts-to-run-git-commands

**Comment by ericsciple** [comment]
closing the issue here. it is not an issue with the code in this repo (the agent).

the label sources checkbox is a server side feature. correct location for feedback specific on the service (server side) is listed here: https://www.visualstudio.com/en-us/docs/build/troubleshooting#i-need-more-help-i-found-a-bug-ive-got-a-suggestion-where-do-i-go
