### ISSUE TITLE
Agent fails when run in same dir as vso-agent

### ISSUE THREAD

**Issue by bc3tech** [Microsoft/vsts-agent#76]
I've configured an agent on OSX via the instructions
I unpacked the same `tar.gz` downloaded in the first step to a separate directory in order to create another agent on the same machine.
When trying to run `./run.sh` from the second directory, I'm met with:
```
An error occured.  Credentials not stored.  Must reconfigure.
```

**Comment by bc3tech** [comment]
looks like the core issue here is if you uninstall an agent created with the vso-agent codebase, remove the files, unpack to the *same directory the vso-agent was in*, then try to do `./run.sh` you'll hit this error. Using a dir w/ a different name works.

**Comment by bryanmacfarlane** [comment]
That makes sense since all running as a service does is conveniently create the plist pointing to that dir.  Unintstalling an agent doesn't hook any code - it's just delete dir.  So, I'm open for suggestions here.  Should I print something like, hey, we created this plist for you here as a convenience.  If you ever delete the agent don't forget to clean it up?  We have a service stop command which would clean it up.  Perhaps a delete agent or unconfigure command and that will look up and delete?  I'm open to ideas ...

**Comment by bryanmacfarlane** [comment]
How did you remove the files?  with the gui?

**Comment by bryanmacfarlane** [comment]
The docs detail doing mkdir && cd.  That ensures a clean slate.  With mixed files from different agents overlaid, the behavior will always be undefined

Try latest update
