### ISSUE TITLE
Agent.Worker and Microsoft.VisualStudio.Services.Agent not on NuGet

### ISSUE THREAD

**Issue by aumanjoa** [Microsoft/vsts-agent#767]
Hi Agent Team,

I would like to use some functionality from the [Agent.Worker](https://github.com/Microsoft/vsts-agent/tree/master/src/Agent.Worker) and from [Microsoft.VisualStudio.Services.Agent](https://github.com/Microsoft/vsts-agent/tree/master/src/Microsoft.VisualStudio.Services.Agent) in my .net core programm.

But I was not able to find the packages on NuGet.  Can you please share the NuGet package link or is there a reason behind to not share this lib´s on NuGet.

**Comment by ericsciple** [comment]
The agent isn't maintained as an SDK. The public interfaces are subject to change between releases.

What functionality are you looking to leverage?

**Comment by bryanmacfarlane** [comment]
Tasks shouldn't call into to binaries owned by the agent.  That's a horrible coupling problem which is why we have a decoupled task lib.

Those aren't published as libraries because they are not an SDK.  They are separate processes in the agent (agent and worker) and the way net core builds self contained exes is it builds dlls and the native exe shims which call them.

**Comment by aumanjoa** [comment]
I have a simple problem.
I want to call other Tasks by an own created task, simply because I want to write the task workflow in Code and NOT in a web frontend. like the "Jenkinsfile" for Jenkins Pipelines 

How I can achieve this? 
I don't have found a way in the task lib to call other tasks. may you can help there.
