### ISSUE TITLE
OS X Sierra Support

### ISSUE THREAD

**Issue by benwalpole** [Microsoft/vsts-agent#804]
## **Agent version and platform**
Version of your agent? Not currently installed
<br>
OS of the machine running the agent? I'm trying to install it on OS X 10.12.1.
<br>
## **VSTS type and version**
VisualStudio.com

## **What's not working?** 
I'm trying to get started installing the agent on OS X Sierra but I'm failing at the first hurdle trying to use home brew to install OpenSSL.

I get an error that usr/local is not writable, I believe this is because of the new rootless mode in Sierra which means I'm not able to make it writable.

I notice that the OS X agent has only been validated on OS X 10.10 and 10.11, do you have any advice on getting this working on 10.12?  
<br>

**Comment by TingluoHuang** [comment]
@benwalpole 
The agent is built for 10.11, but 10.12 should works fine, since Dotnet Core support it.
I found few links for you homebrew  problem, you can take a look.
https://github.com/Homebrew/brew/issues/476
https://github.com/Homebrew/brew/issues/385
https://github.com/Homebrew/legacy-homebrew/issues/49895
