### ISSUE TITLE
TFS  Service Endpoints are not configurable through variables

### ISSUE THREAD

**Issue by aumanjoa** [Microsoft/vsts-agent#814]
Hey Team,

according to the issue described here: 
[https://github.com/Microsoft/vsts-extension-build-release-tasks/issues/33](https://github.com/Microsoft/vsts-extension-build-release-tasks/issues/33)

I am raising the bug for the vsts-agent team as @jessehouwing suggested.
Its not possible to controle TFS Service Endpoints over variables. This is a problem if you want to deploy during release mangement to diffrent Service Endpoints.

Joachim

**Comment by bryanmacfarlane** [comment]
Not an agent issue.  Service endpoints are a service side feature.  Service endpoints come to the agent fully realized.  You have to follow up with the release management team since they work on the service endpoints service side.  I would reactive the item you referenced and followed up with Gopi (the PM for RM that responded).
