### ISSUE TITLE
Include vswhere.exe in vsts-agent distribution / No VS150COMNTOOLS in VS2017

### ISSUE THREAD

**Issue by mfergusonPM9** [Microsoft/vsts-agent#844]
As VS 2017 no longer installs the "VS150COMNTOOLS" (previously "VS140COMNTOOLS") environment variable, it would be great if the vsts-agent platform could include a binary for vswhere.exe with the Windows install to allow for programatic detection of the path for Visual Studio 2017. Please see below for the link on Github and a link to the issue / change.

https://github.com/Microsoft/vswhere

https://blogs.msdn.microsoft.com/vcblog/2017/03/06/finding-the-visual-c-compiler-tools-in-visual-studio-2017/

Thank you!

**Comment by TingluoHuang** [comment]
@mfergusonPM9 
we already use COM API query VS2017 install location.
https://github.com/Microsoft/vsts-agent/blob/master/src/Misc/layoutbin/powershell/Add-VisualStudioCapabilities.ps1#L55

You can create a PR to add `VS150COMNTOOLS` use same idea. :)

**Comment by ericsciple** [comment]
@mfergusonPM9 the agent doesn't add VS140COMNTOOLS as an env var.

**Comment by mfergusonPM9** [comment]
@ericsciple Thanks -- Correct, as I stated above, it was included previously as part of the VS install. Starting with VS 2017, this variable is no longer added to the machine environment. This change poses a bit of a challenge for migrating scripts while still being agnostic to the VS installation location, but I think the work-around provided by @TingluoHuang will work well. Thank you!

**Comment by ericsciple** [comment]
Oh, sorry, you are right. I misread.

Also VS publishes powershell cmdlets now too. The COM API the agent queries is the V1 COM API and sometimes it doesn't pickup an installation that had some errors but is largely usable (launches). The V3 COM API would be better to call. We need to switch the agent to use the V3 API (or vswhere, or the new official cmdlets) but haven't yet.

**Comment by ericsciple** [comment]
If the agent carried vswhere.exe, it would probably be for internal usage only (by agent). Typically the agent doesn't carry external binaries for consumption by tasks or end user scripts, because then it's stuck carrying the binary forever lest it break compat. It also makes it hard to switch version that it carries (if the interface of the external binary changes, then also breaks compat for tasks or scripts depending on the binary).

The agent does publish capabilities, but they are only useful for job routing today. Tasks/scripts don't have access to the capability values (known limitation, but need to work out other limitations wrt capabilities before exposing to tasks/scripts).

**Comment by mfergusonPM9** [comment]
That makes sense, but the product is called Visual Studio .. Agent. :) It feels a bit obtuse that a user would need an external binary or work-around to detect the installation path for Visual Studio. With that said, it's not like the issue is insurmountable... but it also doesn't really lend itself well to automation for the product it is trying to target. My $0.02.

**Comment by ericsciple** [comment]
Hah, good point. I'll fwd on to appropriate folks. I think making capabilities accessible to tasks/scripts is the clean path forward (future work, I don't have a timeframe).
