### ISSUE TITLE
NuGet restore fails with Hosted VS2017 on VSTS

### ISSUE THREAD

**Issue by MartinZikmund** [Microsoft/vsts-agent#869]
## **Agent version and platform**
Hosted VS2017
## **VSTS type and version**
VisualStudio.com
http://omegagoteamservices.visualstudio.com
<br>
## **What's not working?** 
When I include the NuGet Restore version 3.5.0 step in the build configuration, I get the following error:

![image](https://cloud.githubusercontent.com/assets/1075116/24203778/f31bc608-0f16-11e7-926a-c82ee5498ffa.png)

Unfortunately, NuGet 4.0.0 is not available for selection in the editor. 
![image](https://cloud.githubusercontent.com/assets/1075116/24203649/9daac76e-0f16-11e7-877f-9824eb2b92c1.png)

The Visual Studio Build step has Nuget restore option as well, but that is deprecated
![image](https://cloud.githubusercontent.com/assets/1075116/24203710/c42581b8-0f16-11e7-8a07-9a769d70249e.png)

I have tried on two different VSTS accounts and I get the same result.

**Comment by JohnGalt1717** [comment]
This is because nuget needs to be version 4.0 for Hosted2017 but apparently even though they had months to get vsts updated for release day of vs.net 2017 they're just getting around to finally giving us Hosted2017 but haven't updated the nuget commands nor any of the dotnetcore commands.

I'd love to see a road map of when this stuff is going to finally be done and working properly and able to actually build anything with vs.net 2017.

(as a work around, include nuget.exe v4.0 somewhere in your solution and then choose custom and point to that exe and it will get around this for now)

**Comment by ericsciple** [comment]
This is an issue with either the vsts-tasks repo or hosted image, not the agent (this repo). Closing the issue here.
