### ISSUE TITLE
Build agent is misinterpreting the commands with Special characters

### ISSUE THREAD

**Issue by nigurr** [Microsoft/vsts-agent#929]
Tested: Latest agent

If i am writing command to agent with special chars, the agent is not handling them well

```
Powershell task1:
Write-Host "##vso[task.setvariable variable=testSpecial;]b Kthe advanced£rs Àcd8d487331553a317"

Powershell task2:
$expected = "b Kthe advanced£rs Àcd8d487331553a317"
$actual = $Env:testSpecial

Write-Host "Expected: $expected Actual: $actual"
Write-Host "$($expected -eq $actual)"
```
The retrieved value is: b Kthe advanced£rs **A**cd8d487331553a317
The expected value is: b Kthe advanced£rs **À**cd8d487331553a317

This seems to be critical issue as the project names can contain these special chars and when we set these variables internally and retrieve next time, the value is being tampered.

**Comment by ericsciple** [comment]
my guess is it's the process reading the env var. i'm pretty sure the agent accurately interprets stdout (logging command)

**Comment by nigurr** [comment]
@ericsciple I dumped the process variables from process explorer. Its the same. The value is set incorrectly. Either we are storing it incorrectly or we are setting incorrectly. Wish I have time to debug :(

**Comment by ericsciple** [comment]
That character may not be in your code page. This works for me:
PS script 1:
`'##vso[task.setvariable variable=testSpecial]this char ç should work'`

PS script 2:
`$env:testSpecial`

That char is a good test given my setup. The character is supported but the encoded value doesn't align for the common encodings on my box (console host code page 437, system default 1252, and utf8).

Closing since I trust that the `ç` character is an accurate test given my setup.

**Comment by nigurr** [comment]
@ericsciple Sorry my powershell has the charset and simple Console output prints it accurately. This is being caused to one of our customers and internally our RBs are failing when we have special chars in the project name. (not all special chars are causing this). This is legitimate issue rather than powershell encoding
