### ISSUE TITLE
Allow "cross platform" multi-configuration builds

### ISSUE THREAD

**Issue by bbowman** [Microsoft/vsts-agent#972]
The scenario my team has is as follows:

Our project is C++ and needs to build across several different platforms, including iOS. For some of these platforms (mainly iOS), this requires a certain agent to be used to ensure a matching tool chain is available. 

It is a pain to have separate build definitions for each platform that we need and either try to chain them together or have them all report status, test results, etc back to a nice "single dashboard". 

Without the "environments" capability of the release phase, it would at least be feasible using "Conditional Tasks" and "Agent Demands" to set up a single, multi-configuration build if the multi-configuration variable could be used in "Agent Demands" to pick the right agent for the correct "sub build".

Would it be possible to allow for build variables to be used as an Agent Demand condition? Thoughts?

@bryanmacfarlane 

Thanks!

**Comment by bryanmacfarlane** [comment]
We are developing multiple phases in build right now.  Note that it's not an agent issue.

You will also lose visibility of tracking history and results by platform.  The ability to show status by platform:  https://github.com/Microsoft/vsts-tasks/blob/master/README.md since status is hung off of a definition.  While some say that's a pain, it's actually nice to know it's failing on linux but passing on windows.

But, phases will allow you to do that.
