### ISSUE TITLE
Yaml Feature: Caching tasks w/o credentials

### ISSUE THREAD

**Issue by onovotny** [Microsoft/vsts-agent#973]
Reviewing the spec for YAML deserialization here: https://github.com/Microsoft/vsts-agent/blob/a7a1fe8189b20dd5be138e5c65391207260d30eb/docs/preview/yamldeserialization.md#task-version-resolution-and-caching

The spec says that tasks need to be either pre-cached or a TFS/VSTS URL can be provided with credentials for the tasks to be downloaded. I would suggest that tasks available generally on the VSTS Marketplace be retrieved anonymously without any credentials.

The goal should be "build and run" locally by an anon user. Ideally, the VSTS Agent task should be downloadable from a public endpoint as well so we can have a `build.ps1`/`build.sh` script to bootstrap the build. It'll download the agent and then run it all without any user credentials.

/cc @martinwoodward

**Comment by chrisrpatterson** [comment]
Hi Oren,
I think the big difference in concept here is VSTS is not a build engine it is an orchestrator. There are a lot of good build engines that you can download and bootstrap to actually build your code.  The goal of something like VSTS or eve Jenkins for that matter is to orchestrate the build, test and then deployment of your code.  In addition it needs to provide for machine management and reporting.

With that in mind you would invert your statement and the vsts orchestrator should call your build.ps1 which defines your actual build.

**Comment by onovotny** [comment]
@chrisrpatterson I think what I'm saying is that I want to run the full orchestration locally...and that includes build, test, run coverage, etc.

I hate the fact I need to check in my AppVeyor.yml file 20 times in a row as I'm troubleshooting getting the build right. I really wish I could run it all locally to ensure it does what I want.

**Comment by chrisrpatterson** [comment]
In our spec it does allow you to run it locally.  However, the problem is the orchestration might include parallel phases and jobs that run on different agents.  For example lets say I had a Xamarin app and I wanted to have a single definition that built across UWP, Android and iOS. The orchestration can accomplish this from the service utilizing agents and agent pools but it is not something you can realistically run locally.

**Comment by bryanmacfarlane** [comment]
Yeah - so run locally is parallelism of 1.

Also note that tasks come from your account/server.  They are installed into the server via extensions from the market place.  And then referenced in the definition (be it web or yaml) by locking to major version channel of all versions that have been installed in your back end.  Alternatively for yaml we will support checking in the task (since one key motivation for yaml is locking down and following branches etc...) and potentially point to a git url + ref / commit.

Admin still controls which extensions are used/installed in their account.

**Comment by onovotny** [comment]
I'm still not sure why this can't all be done without credentials? I.e., reference a particular version of a task from the market place if it's a "public/free" task?

**Comment by bryanmacfarlane** [comment]
When they are installed into your account, they are installed into an append only list of immutable versions in build.  You can bind to any major version channel of task versions that you have previously installed, gotten updates for.  Extensions are a delivery mechanism for build tasks.  Also, the version of an extension has no bearing on tasks - a version of an extension can carry multiple tasks, each with their own versions.  So, there is no way to ask the market place for version channel 2 of task x.  That would be like asking a bunch of msi installers to give me version 3 of a certain com component that they carry.  You're asking for version 2.x of a task, not for version 2.x of the extension that carries multiple contributions.

But as I covered above, you can checkin tasks or have on disk.  So, create a yaml file - in a relative dir locally, add the tasks, run local - no need to contact the server.  You can choose to checkin the yaml and even copies of the tasks to lock.  Now you can lock down your process and the tasks, go back build an old branch (service branch) and know the process didn't change. 

That works for our tasks or any tasks you can acquire the raw files for - not extensions from the market place.

As noted above, we also have the strict requirement that admins need to control what extensions are used on their server.  So, extensions must be installed in your account to be available for use in orchestrations.
